apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-tshi
  namespace: appstudio-e2e-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: jvm-build-suite-application-lajs
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: jvm-build-suite-component-tshi
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: jvm-build-suite-component-tshi-
      labels:
        build.appstudio.openshift.io/application: jvm-build-suite-application-lajs
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: jvm-build-suite-component-tshi
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: appstudio-e2e-test
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/hacbs-test-project
      - name: output-image
        value: quay.io/redhat-appstudio-qe/test-images:552c7e79f9794790b3ba2df4f6b021c1-$(tt.params.git-revision)
      - name: revision
        value: main
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0
        name: java-builder
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: jvm-build-suite-component-tshi/$(tt.params.git-revision)
    status: {}
status: {}
